STORES_JSON = {
    "Data": [
        {
            "BranchCode": "13438",
            "OutletCode": "438",
            "StoreCode": "MET",
            "StoreName": "The Metropolis",
            "Address": "9 North Buona Vista Drive #01-13/14, The Metropolis, Singapore",
            "PostalCode": "138588",
            "PhoneNo": "6910 1209",
            "Longitude": "103.79130178222705",
            "Latitude": "1.3058152595075494",
            "MONPStatus": False,
            "DeliveryStatus": False,
            "ServiceHours": [
                {
                    "DayOfWeekString": "MONDAY",
                    "DayOfWeek": 1,
                    "OpenFrom": "07:00:00",
                    "OpenTo": "20:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "TUESDAY",
                    "DayOfWeek": 2,
                    "OpenFrom": "07:00:00",
                    "OpenTo": "20:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "WEDNESDAY",
                    "DayOfWeek": 3,
                    "OpenFrom": "07:00:00",
                    "OpenTo": "20:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "THURSDAY",
                    "DayOfWeek": 4,
                    "OpenFrom": "07:00:00",
                    "OpenTo": "20:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "FRIDAY",
                    "DayOfWeek": 5,
                    "OpenFrom": "07:00:00",
                    "OpenTo": "20:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "SATURDAY",
                    "DayOfWeek": 6,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "17:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "SUNDAY",
                    "DayOfWeek": 7,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "17:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "PUBLIC_HOLIDAY",
                    "DayOfWeek": 8,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "17:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "EVE_OF_PUBLIC_HOLIDAY",
                    "DayOfWeek": 9,
                    "OpenFrom": "07:00:00",
                    "OpenTo": "20:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
            ],
            "Amenities": {
                "NitroColdBrew": False,
                "StarbucksReserve": False,
                "MobileOrderandPay": True,
                "FreeWifi": True,
                "PourOverBrew": False,
            },
        },
        {
            "BranchCode": "13412",
            "OutletCode": "412",
            "StoreCode": "RP",
            "StoreName": "Rochester Park",
            "Address": "37 Rochester Drive, Rochester Park, Singapore",
            "PostalCode": "138640",
            "PhoneNo": "6910 1165",
            "Longitude": "103.787771",
            "Latitude": "1.305575",
            "MONPStatus": False,
            "DeliveryStatus": False,
            "ServiceHours": [
                {
                    "DayOfWeekString": "MONDAY",
                    "DayOfWeek": 1,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "22:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "TUESDAY",
                    "DayOfWeek": 2,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "22:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "WEDNESDAY",
                    "DayOfWeek": 3,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "22:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "THURSDAY",
                    "DayOfWeek": 4,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "22:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "FRIDAY",
                    "DayOfWeek": 5,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "23:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "SATURDAY",
                    "DayOfWeek": 6,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "23:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "SUNDAY",
                    "DayOfWeek": 7,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "22:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "PUBLIC_HOLIDAY",
                    "DayOfWeek": 8,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "22:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
                {
                    "DayOfWeekString": "EVE_OF_PUBLIC_HOLIDAY",
                    "DayOfWeek": 9,
                    "OpenFrom": "07:30:00",
                    "OpenTo": "23:00:00",
                    "Is24Hours": False,
                    "IsClosed": False,
                },
            ],
            "Amenities": {
                "FreeWifi": True,
                "MobileOrderandPay": True,
                "NitroColdBrew": False,
                "PourOverBrew": False,
                "StarbucksReserve": False,
            },
        },
    ]
}
